name: buildtest
on: [push]
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libauthen-sasl-perl libnet-ldap-perl libpalm-perl libvformat-dev abook
      - run: ./configure
      - run: make
      - run: make test
